# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0005_person_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='slug',
            new_name='sa_id',
        ),
    ]
