# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0008_auto_20171001_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=120),
        ),
    ]
